baseURL = "http://thomasjohander.info/"
languageCode = "en-us"
title = "Thomas Johander Resume"
theme="hugo-resume"

[params]
  firstName = "Thomas"
  lastName = "Johander"
  email = "tjohander@gmail.com"
